services:
   whatsapp:
     build: ./whatsapp
     container_name: back
     networks:
      - scmv
     ports: 
      - 5000:5000
     environment:
      - PYTHONUNBUFFERED=0

   db:
     image: mysql
     container_name: data
     restart: always
     networks:
      - scmv
     ports: 
      - 3307:3306
     volumes:
      - db-data:/var/lib/mysql
     env_file:
      - .env
     environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?Variable not set}
      - MYSQL_DATABASE=${MYSQL_DATABASE?Variable not set}
      - MYSQL_USER=${MYSQL_USER?Variable not set}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Variable not set}

volumes:
  db-data:

networks:
  scmv:
    name: scmv-net